### ISSUE TITLE
Download link is now busted

### ISSUE THREAD

**Issue by rick** [boxen/puppet-kindle#10]
Not sure how long it's been the case, but going to the canonical link: http://kindleformac.amazon.com/40381/KindleForMac.dmg results in an "Access Denied" error page:

![](https://github-images.s3.amazonaws.com/skitch/kindleformac.amazon.com_40381_KindleForMac.dmg-20141216-210719.jpg)

I haven't been able, so far, to find another direct download link -- all the links I can find end up sending me to the App Store. :-1:

**Comment by jacobbednarz** [comment]
Deprecated in favour of [brewcask][1] and [Boxen's in built support for
homebrew/brewcask][2].

[1]: https://caskroom.github.io/
[2]: https://github.com/boxen/puppet-boxen/blob/master/manifests/personal.pp#L14-L17
